imports:
    - {resource: ../../src/SpamTrap/ClassifierBundle/Resources/config/services.yml}

services:
    application_loader:
        class: SymfonyBridge\CommandLoader

    application:
        class: SymfonyBridge\ContainerAwareApplication
        arguments: ['SpamTrap', ~]
        configurator: ["@application_loader", loadCommands]

    elasticsearch:
        class: Elasticsearch\Client
        arguments:
            - %elastic_connection%
